services:
  postgres:
    image: postgres:17
    container_name: clinic_management_postgres

    environment:
      POSTGRES_DB: clinic_management_database
      POSTGRES_USER: clinic_management_system
      POSTGRES_PASSWORD: clinic_management_system_password

    ports:
      - "5430:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

  redis:
    image: redis:7
    container_name: clinic_management_redis

    ports:
      - "6379:6379"

    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: clinic_management_rabbitmq

    ports:
      - "5672:5672"
      - "15672:15672"

    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

    restart: unless-stopped

volumes:
  postgres_data: