"""add lunch for schedule model

Revision ID: 23aec8f86271
Revises: ce86fc77ee58
Create Date: 2026-07-14 10:14:10.837792

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "23aec8f86271"
down_revision: str | Sequence[str] | None = "ce86fc77ee58"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("schedules", sa.Column("lunch_start_time", sa.Time(), nullable=True))
    op.add_column("schedules", sa.Column("lunch_end_time", sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("schedules", "lunch_end_time")
    op.drop_column("schedules", "lunch_start_time")
    # ### end Alembic commands ###
