"""create drug and disease models

Revision ID: 293e569a7f73
Revises: 48daa54f4caf
Create Date: 2026-06-11 15:17:40.360899

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "293e569a7f73"
down_revision: str | Sequence[str] | None = "48daa54f4caf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
