"""create attachment model

Revision ID: 2de33373d3f4
Revises: 5293f0da9067
Create Date: 2026-06-11 20:56:08.233083

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "2de33373d3f4"
down_revision: str | Sequence[str] | None = "5293f0da9067"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
