"""fix phone number field in users model

Revision ID: 3567ab5e39e6
Revises: 2de33373d3f4
Create Date: 2026-06-16 18:09:53.544898

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3567ab5e39e6"
down_revision: str | Sequence[str] | None = "2de33373d3f4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "phone", existing_type=sa.VARCHAR(length=20), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "phone", existing_type=sa.VARCHAR(length=20), nullable=False
    )
    # ### end Alembic commands ###
