"""update diagnosis model

Revision ID: 820045600dbd
Revises: 83d5d8f790dd
Create Date: 2026-07-03 16:04:56.343054

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "820045600dbd"
down_revision: str | Sequence[str] | None = "83d5d8f790dd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "diagnoses", sa.Column("prescription_id", sa.Integer(), nullable=False)
    )
    op.drop_constraint(
        op.f("diagnoses_appointment_id_fkey"), "diagnoses", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "diagnoses", "prescriptions", ["prescription_id"], ["id"]
    )
    op.drop_column("diagnoses", "appointment_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "diagnoses",
        sa.Column("appointment_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "diagnoses", type_="foreignkey")
    op.create_foreign_key(
        op.f("diagnoses_appointment_id_fkey"),
        "diagnoses",
        "appointments",
        ["appointment_id"],
        ["id"],
    )
    op.drop_column("diagnoses", "prescription_id")
    # ### end Alembic commands ###
