"""update drug model

Revision ID: 83d5d8f790dd
Revises: 3567ab5e39e6
Create Date: 2026-06-28 23:20:30.691793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from common.enums.dosage_form import DosageForm
revision: str = '83d5d8f790dd'
dosage_form_enum = postgresql.ENUM(
    DosageForm,
    name="dosage_form",
)
down_revision: Union[str, Sequence[str], None] = '3567ab5e39e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    dosage_form_enum.create(bind, checkfirst=True)
    op.create_table('attachments',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=128), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_mime_type', sa.String(length=128), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('drugs', sa.Column('international_name', sa.String(length=128), nullable=False))
    op.add_column('drugs', sa.Column('dosage_form', sa.Enum('TABLET', 'CAPSULE', 'SYRUP', 'INJECTION', 'OINTMENT', 'GEL', 'DROPS', name='dosage_form'), nullable=False))
    op.add_column('drugs', sa.Column('strength', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drugs', 'strength')
    op.drop_column('drugs', 'dosage_form')
    bind = op.get_bind()
    dosage_form_enum.drop(bind, checkfirst=True)
    op.drop_column('drugs', 'international_name')
    op.drop_table('attachments')
    # ### end Alembic commands ###
