"""make schedule absence description nullable

Revision ID: 8b2699d26051
Revises: f6f5e92a09de
Create Date: 2026-07-25 21:52:01.287550

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8b2699d26051"
down_revision: str | Sequence[str] | None = "f6f5e92a09de"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "schedule_absences", "description", existing_type=sa.TEXT(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "schedule_absences", "description", existing_type=sa.TEXT(), nullable=False
    )
    # ### end Alembic commands ###
