"""update prescription_item and diagnosis models

Revision ID: ce86fc77ee58
Revises: 820045600dbd
Create Date: 2026-07-05 14:26:11.057305

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ce86fc77ee58"
down_revision: str | Sequence[str] | None = "820045600dbd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("diagnoses_prescription_id_fkey"), "diagnoses", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "diagnoses",
        "prescriptions",
        ["prescription_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("prescription_items_prescription_id_fkey"),
        "prescription_items",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "prescription_items",
        "prescriptions",
        ["prescription_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "prescription_items", type_="foreignkey")
    op.create_foreign_key(
        op.f("prescription_items_prescription_id_fkey"),
        "prescription_items",
        "prescriptions",
        ["prescription_id"],
        ["id"],
    )
    op.drop_constraint(None, "diagnoses", type_="foreignkey")
    op.create_foreign_key(
        op.f("diagnoses_prescription_id_fkey"),
        "diagnoses",
        "prescriptions",
        ["prescription_id"],
        ["id"],
    )
    # ### end Alembic commands ###
