"""create appointment model

Revision ID: e5e7f2b36633
Revises: 37f08ba08e15
Create Date: 2026-06-11 17:18:05.040444

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e5e7f2b36633"
down_revision: str | Sequence[str] | None = "37f08ba08e15"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "appointments",
        sa.Column("patient_id", sa.Integer(), nullable=False),
        sa.Column("doctor_id", sa.Integer(), nullable=False),
        sa.Column("slot_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "SCHEDULED",
                "COMPLETED",
                "CANCELED",
                "NO_SHOW",
                name="appointment_status",
            ),
            nullable=False,
        ),
        sa.Column("complaint", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("doctor_id <> patient_id", name="ck_doctor_not_patient"),
        sa.ForeignKeyConstraint(["doctor_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["patient_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["slot_id"], ["schedule_slots.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slot_id", name="uq_appointment_slot"),
    )
    op.drop_constraint(
        op.f("schedule_absences_doctor_id_fkey"),
        "schedule_absences",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "schedule_absences", "users", ["doctor_id"], ["id"], ondelete="RESTRICT"
    )
    op.drop_constraint(
        op.f("schedule_slots_schedule_id_fkey"), "schedule_slots", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("schedule_slots_doctor_id_fkey"), "schedule_slots", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "schedule_slots", "users", ["doctor_id"], ["id"], ondelete="RESTRICT"
    )
    op.create_foreign_key(
        None,
        "schedule_slots",
        "schedules",
        ["schedule_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_constraint(
        op.f("schedules_doctor_id_fkey"), "schedules", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "schedules", "users", ["doctor_id"], ["id"], ondelete="RESTRICT"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "schedules", type_="foreignkey")
    op.create_foreign_key(
        op.f("schedules_doctor_id_fkey"), "schedules", "users", ["doctor_id"], ["id"]
    )
    op.drop_constraint(None, "schedule_slots", type_="foreignkey")
    op.drop_constraint(None, "schedule_slots", type_="foreignkey")
    op.create_foreign_key(
        op.f("schedule_slots_doctor_id_fkey"),
        "schedule_slots",
        "users",
        ["doctor_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("schedule_slots_schedule_id_fkey"),
        "schedule_slots",
        "schedules",
        ["schedule_id"],
        ["id"],
    )
    op.drop_constraint(None, "schedule_absences", type_="foreignkey")
    op.create_foreign_key(
        op.f("schedule_absences_doctor_id_fkey"),
        "schedule_absences",
        "users",
        ["doctor_id"],
        ["id"],
    )
    op.drop_table("appointments")
    # ### end Alembic commands ###
