"""fix attachment model

Revision ID: f6f5e92a09de
Revises: c8ff0ae53382
Create Date: 2026-07-20 13:23:18.981178

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f6f5e92a09de"
down_revision: str | Sequence[str] | None = "c8ff0ae53382"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "attachments", sa.Column("appointment_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(
        None,
        "attachments",
        "appointments",
        ["appointment_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "attachments", type_="foreignkey")
    op.drop_column("attachments", "appointment_id")
    # ### end Alembic commands ###
